/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package PrimeServerHttp;


import java.net.InetSocketAddress;
import java.util.*;
import java.net.InetSocketAddress;
import java.util.*;
import java.io.*;
import java.util.logging.*;

import com.google.common.io.Resources;
import com.sun.net.httpserver.*;

public class PrimeServerHttp {

    // static logger 
    public static final Logger LOG = Logger.getLogger(PrimeServerHttp.class.getName());

    // start web server
    public static void main(String[] args) throws Exception {

        try {
            HttpServer server = HttpServer.create(new InetSocketAddress(8080), 0);
            LOG.info("HTTP: Server started");
            server.createContext("/", new LandingPageHandler());
            server.createContext("/prime", new PrimeContextHandler());
            server.setExecutor(null); // creates a default executor
            server.start();
        } catch (IOException ex) {
            LOG.log(Level.ALL, ex.getMessage());
        }
    }
    
    //Landing page handler for default server greeting
    static class LandingPageHandler implements HttpHandler{
        @Override
        public void handle(HttpExchange request) throws IOException{
            LOG.info(System.getProperty("user.dir"));
            String resp = "";
            
            try(var bReader = new BufferedReader(new InputStreamReader(new FileInputStream(new File("resources/index.html"))))){
                String line;
            
                while((line = bReader.readLine()) != null){
                    resp += line;
                }
                
                bReader.close();
        } catch (FileNotFoundException e){
            e.printStackTrace();
        } catch (IOException e){
            e.printStackTrace();
        }

            request.getResponseHeaders().set("Content-Type", "text/html");
            request.sendResponseHeaders(200, resp.length());
            OutputStream os = request.getResponseBody();
            os.write(resp.getBytes());
            os.close();
        }
    }

    // registered handler class for named context
    static class PrimeContextHandler implements HttpHandler {

        @Override
        public void handle(HttpExchange request) throws IOException {
            LOG.info(request.getRequestMethod() + " " + request.getRequestURI().toString());
            //set to text/html for machine to machine communication
            request.getResponseHeaders().set("Content-Type", "text/html");

            String response = "";
            // handle request type
            if (request.getRequestMethod().equalsIgnoreCase("GET")) {
                response = handleGET(request);
                if (response.equals("")) {
                    request.sendResponseHeaders(404, 0); // 404 bad request
                } else {
                    request.sendResponseHeaders(200, 0); // 200 Ok
                }
            } else {
                request.sendResponseHeaders(501, 0); //  501 - not implemented
            }
            // write response and close
            request.getResponseBody().write(response.getBytes());
            request.getResponseBody().close();

        }

        // handle a HTTP GET request
        public static String handleGET(HttpExchange request) throws IOException, NumberFormatException {
            Map<String, String> parms = getQueryParameters(request);

            String number = parms.getOrDefault("Number", "");

            if (!number.equals("")) {
                // call isPrimeNumber function
                Boolean isPrime = isPrimeNumber(Integer.parseInt(number));
                return String.valueOf(isPrime);
            }
            return "";
        }

        // parse request query parameters into a Map
        public static Map<String, String> getQueryParameters(HttpExchange request) {
            Map<String, String> result = new HashMap<>();
            String query = request.getRequestURI().getQuery();
            if (query != null) {
                for (String param : query.split("&")) {
                    String pair[] = param.split("=");
                    if (pair.length > 1) {
                        result.put(pair[0], pair[1]);
                    } else {
                        result.put(pair[0], "");
                    }
                }
            }
            return result;
        }
    }// class PrimeContextHandler 


    // utility method to check if a number is prime
    public static boolean isPrimeNumber(int number) {
        if (number == 2 || number == 3) {
            return true;
        }
        if (number % 2 == 0) {
            return false;
        }
        int sqrt = (int) Math.sqrt(number) + 1;
        for (int i = 3; i < sqrt; i += 2) {
            if (number % i == 0) {
                return false;
            }
        }
        return true;
    }

}