/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package PrimeServerHttp;

import org.junit.Test;
import static org.junit.Assert.*;

public class PrimeServerHttpTest{
    @Test public void testAppHasAGreeting() {
        PrimeServerHttpTest classUnderTest = new PrimeServerHttpTest();
        assertEquals(1, 1);
    }
}
